version: '3.7'
services:

  frontend:
    container_name: frontend
    ports:
      - 80:80
    build: ./frontend
    restart: always
    depends_on:
      - backend

  backend: 
    container_name: backend
    ports: 
      - 8081:8081
    build: ./backend
    restart: always

  postgres:
    image: postgres:11.2
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mybookshelf
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  pgadmin4:
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - ./database/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres
    restart: always